# Generated by Django 2.2.2 on 2019-06-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='amount',
            new_name='user',
        ),
    ]
