# Generated by Django 2.2.2 on 2019-06-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190626_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='typeaccount',
            field=models.CharField(choices=[('1', 'Savings'), ('2', 'Current')], help_text='type of account', max_length=100, null=True),
        ),
    ]
