# Generated by Django 2.2.2 on 2019-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_balance_typeaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
