# Generated by Django 2.2.2 on 2019-06-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_balance_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='balance',
            table='my_balance',
        ),
    ]
