# Generated by Django 2.2.2 on 2019-06-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190626_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelTable(
            name='balance',
            table=None,
        ),
    ]
