# Generated by Django 2.2.2 on 2019-06-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190630_1042'),
        ('accounts', '0009_auto_20190626_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cartproducts',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
