# Generated by Django 2.2.2 on 2019-07-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_cartproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cartproducts',
        ),
    ]
