# Generated by Django 2.2.2 on 2019-06-26 03:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='generated unique id for product', primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='generated unique id for product', primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='generated unique id for product', primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=30)),
            ],
        ),
    ]
