# Generated by Django 2.2.2 on 2019-06-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='content',
            field=models.CharField(default='The HP 245 G6 Laptop renders performance and multi-tasking efficiency with its integrated 4 GB RAM. This device is powered by a reliable 7th Generation AMD A9-9420 that takes care of all its processing needs. Its hard drive provides storage space for digital content. Also, this laptop features a convenient 35.56cm(14-inch) display that provides a clear view of files, apps, and documents.', help_text='Product discription', max_length=5000),
        ),
        migrations.AddField(
            model_name='laptop',
            name='link',
            field=models.CharField(default='https://via.placeholder.com/225x225', help_text='Image Link', max_length=1100),
        ),
        migrations.AddField(
            model_name='phone',
            name='content',
            field=models.CharField(default='Effortlessly manage your busy schedule with the iPhone 6. This mobile phone has 16 GB of built-in memory, so you can store your music, apps, and more. Featuring an 8-megapixel resolution camera, it lets you document your travels and experiences in impressive detail. Stay connected and entertained using this iPhone 6. This device is locked to AT&T and compatible with Cricket, metroPCS, T-Mobile Carriers.', help_text='Product discription', max_length=5000),
        ),
        migrations.AddField(
            model_name='phone',
            name='link',
            field=models.CharField(default='https://via.placeholder.com/225x225', help_text='Image Link', max_length=1100),
        ),
        migrations.AddField(
            model_name='watch',
            name='content',
            field=models.TextField(default='Meet Fitbit Versa—an all-day companion that helps you live your best life. This lightweight, water-resistant smartwatch empowers you to reach health and fitness goals with actionable insights, personalized guidance, on-screen workouts and more. Run your day with notifications, quick replies, apps, music and 4+ day battery life* Plus, wear it your way with fresh accessories and clock faces. *Battery life varies with use and other factors.', help_text='Product discription', max_length=5000),
        ),
        migrations.AddField(
            model_name='watch',
            name='link',
            field=models.CharField(default='https://via.placeholder.com/225x225', help_text='Image Link', max_length=9100),
        ),
    ]
