# Generated by Django 2.2.2 on 2019-06-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='content',
            field=models.TextField(default='The HP 245 G6 Laptop renders performance and multi-tasking efficiency with its integrated 4 GB RAM. This device is powered by a reliable 7th Generation AMD A9-9420 that takes care of all its processing needs. Its hard drive provides storage space for digital content. Also, this laptop features a convenient 35.56cm(14-inch) display that provides a clear view of files, apps, and documents.', help_text='Product discription', max_length=5000),
        ),
        migrations.AlterField(
            model_name='phone',
            name='content',
            field=models.TextField(default='Effortlessly manage your busy schedule with the iPhone 6. This mobile phone has 16 GB of built-in memory, so you can store your music, apps, and more. Featuring an 8-megapixel resolution camera, it lets you document your travels and experiences in impressive detail. Stay connected and entertained using this iPhone 6. This device is locked to AT&T and compatible with Cricket, metroPCS, T-Mobile Carriers.', help_text='Product discription', max_length=5000),
        ),
    ]
