# Generated by Django 2.2.2 on 2019-07-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_account_cartproducts'),
        ('products', '0005_auto_20190630_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
