# Generated by Django 2.2.2 on 2019-07-01 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='generated unique id for product', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pro_id', models.CharField(max_length=100)),
            ],
        ),
    ]
